const IMG = (city) => `https://source.unsplash.com/featured/1200x600/?${city},morocco,travel`

export const CITIES_DATA = {
  marrakech: {
    slug: 'marrakech', name: 'Marrakech',
    airport: 'RAK - Marrakech Menara', region: 'Marrakech-Safi',
    description: 'Car rental and transfer in Marrakech — airport pickup, city transport, and excursions to the Atlas Mountains and Essaouira.',
    longDescription: 'Marrakech is the most visited city in Morocco. Whether you arrive at Menara Airport or need transport to your riad in the Medina, Golden Trans offers modern vehicles with or without a driver for a stress-free stay.',
    landmarks: ['Jemaa el-Fnaa', 'Majorelle Garden', 'Bahia Palace', 'Koutoubia Mosque', 'Atlas Mountains'],
    popularRoutes: [
      { from: 'Marrakech Airport (RAK)', to: 'Marrakech Medina' },
      { from: 'Marrakech', to: 'Essaouira' },
      { from: 'Marrakech', to: 'Casablanca' },
      { from: 'Marrakech', to: 'Ourika Valley' },
    ],
    image: 'https://images.unsplash.com/photo-1597212618440-806262de4f6b?w=1200&q=80',
  },
  casablanca: {
    slug: 'casablanca', name: 'Casablanca',
    airport: 'CMN - Casablanca Mohammed V', region: 'Casablanca-Settat',
    description: 'Car rental and transfer in Casablanca — business travel, airport shuttles, and city transportation with professional drivers.',
    longDescription: 'Casablanca is Morocco\'s economic hub. From Mohammed V Airport to the Hassan II Mosque and the business district, Golden Trans provides reliable transport for professionals and visitors alike.',
    landmarks: ['Hassan II Mosque', 'Corniche', 'Habous Quarter', 'Morocco Mall', 'Old Medina'],
    popularRoutes: [
      { from: 'Casablanca Airport (CMN)', to: 'Casablanca City Center' },
      { from: 'Casablanca', to: 'Rabat' },
      { from: 'Casablanca', to: 'Marrakech' },
      { from: 'Casablanca', to: 'El Jadida' },
    ],
    image: 'https://images.unsplash.com/photo-1580674285054-bed31e145f59?w=1200&q=80',
  },
  rabat: {
    slug: 'rabat', name: 'Rabat',
    airport: 'RBA - Rabat Salé', region: 'Rabat-Salé-Kenitra',
    description: 'Car rental and transfer in Rabat — airport transfers, city tours, and connections to nearby cities.',
    longDescription: 'As the capital of Morocco, Rabat offers a blend of modern administration and historical heritage. Golden Trans ensures comfortable travel from Rabat-Salé Airport to anywhere in the city and beyond.',
    landmarks: ['Hassan Tower', 'Royal Palace', 'Chellah', 'Kasbah of the Udayas', 'Mohammed VI Museum'],
    popularRoutes: [
      { from: 'Rabat Airport (RBA)', to: 'Rabat City Center' },
      { from: 'Rabat', to: 'Casablanca' },
      { from: 'Rabat', to: 'Tangier' },
      { from: 'Rabat', to: 'Fes' },
    ],
    image: 'https://images.unsplash.com/photo-1582477668395-7c6a1c05ac86?w=1200&q=80',
  },
  fes: {
    slug: 'fes', name: 'Fes',
    airport: 'FEZ - Fes Saïss', region: 'Fes-Meknes',
    description: 'Car rental and transfer in Fes — airport pickup, Medina transport, and trips to Meknes, Volubilis, and the Middle Atlas.',
    longDescription: 'Fes is the cultural and spiritual heart of Morocco. With the oldest university in the world and a UNESCO-listed Medina, Golden Trans helps you explore Fes comfortably from Fes-Saïss Airport.',
    landmarks: ['Al Quaraouiyine Mosque', 'Blue Gate', 'Chouara Tannery', 'Bou Inania Madrasa', 'Merenid Tombs'],
    popularRoutes: [
      { from: 'Fes Airport (FEZ)', to: 'Fes Medina' },
      { from: 'Fes', to: 'Meknes' },
      { from: 'Fes', to: 'Chefchaouen' },
      { from: 'Fes', to: 'Ifrane' },
    ],
    image: 'https://images.unsplash.com/photo-1552679356-5e24abfbd4eb?w=1200&q=80',
  },
  tangier: {
    slug: 'tangier', name: 'Tangier',
    airport: 'TNG - Tangier Ibn Battouta', region: 'Tangier-Tetouan-Al Hoceima',
    description: 'Car rental and transfer in Tangier — port and airport transport, city tours, and routes to Chefchaouen and the coast.',
    longDescription: 'Tangier is the gateway between Africa and Europe. Golden Trans provides seamless transport from Tangier Ibn Battouta Airport and the port to hotels, business meetings, and nearby coastal towns.',
    landmarks: ['Cap Spartel', 'Hercules Cave', 'Grand Socco', 'American Legation Museum', 'Tangier Medina'],
    popularRoutes: [
      { from: 'Tangier Airport (TNG)', to: 'Tangier City Center' },
      { from: 'Tangier', to: 'Chefchaouen' },
      { from: 'Tangier', to: 'Tetouan' },
      { from: 'Tangier', to: 'Asilah' },
    ],
    image: 'https://images.unsplash.com/photo-1580136579312-94651dfd596d?w=1200&q=80',
  },
  agadir: {
    slug: 'agadir', name: 'Agadir',
    airport: 'AGA - Agadir Al Massira', region: 'Souss-Massa',
    description: 'Car rental and transfer in Agadir — airport shuttles, beach resort transport, and excursions to Taghazout and Paradise Valley.',
    longDescription: 'Agadir is Morocco\'s premier beach destination. With its sunny climate and surf spots like Taghazout, Golden Trans makes it easy to get from Agadir Al Massira Airport to your resort or to explore the Souss-Massa region.',
    landmarks: ['Agadir Beach', 'Agadir Marina', 'Souss-Massa National Park', 'Taghazout', 'Paradise Valley'],
    popularRoutes: [
      { from: 'Agadir Airport (AGA)', to: 'Agadir City Center' },
      { from: 'Agadir', to: 'Taghazout' },
      { from: 'Agadir', to: 'Taroudant' },
      { from: 'Agadir', to: 'Essaouira' },
    ],
    image: 'https://images.unsplash.com/photo-1590725140244-1d781586edad?w=1200&q=80',
  },
  chefchaouen: {
    slug: 'chefchaouen', name: 'Chefchaouen',
    airport: 'TNG - Tangier Ibn Battouta (2h)', region: 'Tangier-Tetouan-Al Hoceima',
    description: 'Car rental and transfer to Chefchaouen — the Blue Pearl of Morocco. Scenic mountain routes from Tangier, Fes, and Tetouan.',
    longDescription: 'Chefchaouen is famous for its striking blue-washed streets and buildings. Nestled in the Rif Mountains, it is one of Morocco\'s most photographed destinations. Golden Trans offers comfortable transfers from nearby airports and cities.',
    landmarks: ['Blue Medina', 'Outa el Hammam Square', 'Kasbah Museum', 'Spanish Mosque', 'Rif Mountains'],
    popularRoutes: [
      { from: 'Tangier', to: 'Chefchaouen' },
      { from: 'Fes', to: 'Chefchaouen' },
      { from: 'Tetouan', to: 'Chefchaouen' },
      { from: 'Casablanca', to: 'Chefchaouen' },
    ],
    image: IMG('chefchaouen'),
  },
  essaouira: {
    slug: 'essaouira', name: 'Essaouira',
    airport: 'RAK - Marrakech Menara (2.5h)', region: 'Marrakech-Safi',
    description: 'Car rental and transfer in Essaouira — coastal city transfers, beach resort transport, and wind sports destination access.',
    longDescription: 'Essaouira is a charming coastal city known for its Portuguese fortifications, vibrant arts scene, and world-class windsurfing. Golden Trans provides reliable transfers from Marrakech and Agadir.',
    landmarks: ['Skala de la Ville', 'Essaouira Medina', 'Port of Essaouira', 'Mogador Island', 'Taghazout surf spot'],
    popularRoutes: [
      { from: 'Marrakech', to: 'Essaouira' },
      { from: 'Essaouira', to: 'Agadir' },
      { from: 'Essaouira', to: 'Marrakech Airport (RAK)' },
      { from: 'Essaouira', to: 'Taghazout' },
    ],
    image: IMG('essaouira'),
  },
  meknes: {
    slug: 'meknes', name: 'Meknes',
    airport: 'FEZ - Fes Saïss (1h)', region: 'Fes-Meknes',
    description: 'Car rental and transfer in Meknes — imperial city tours, Volubilis ruins, and connections to Fes and Rabat.',
    longDescription: 'Meknes is one of Morocco\'s four imperial cities, featuring grand gates, massive walls, and the stunning Heri es-Souani granaries. Golden Trans connects you to Meknes from Fes-Saïss Airport and nearby cities.',
    landmarks: ['Bab Mansour', 'Heri es-Souani', 'Mausoleum of Moulay Ismail', 'Place el-Hedim', 'Volubilis'],
    popularRoutes: [
      { from: 'Fes', to: 'Meknes' },
      { from: 'Meknes', to: 'Volubilis' },
      { from: 'Meknes', to: 'Rabat' },
      { from: 'Meknes', to: 'Ifrane' },
    ],
    image: IMG('meknes'),
  },
  ouarzazate: {
    slug: 'ouarzazate', name: 'Ouarzazate',
    airport: 'OZZ - Ouarzazate', region: 'Drâa-Tafilalet',
    description: 'Car rental and transfer in Ouarzazate — gateway to the Sahara, film studio tours, and Ait Ben Haddou excursions.',
    longDescription: 'Ouarzazate is the gateway to the Sahara Desert and a major film location known as "Morocco\'s Hollywood." Golden Trans offers transfers from Ouarzazate Airport to the city, Ait Ben Haddou, and desert camps.',
    landmarks: ['Ait Ben Haddou', 'Atlas Film Studios', 'Taourirt Kasbah', 'Fint Oasis', 'Draa Valley'],
    popularRoutes: [
      { from: 'Ouarzazate Airport (OZZ)', to: 'Ouarzazate City' },
      { from: 'Ouarzazate', to: 'Ait Ben Haddou' },
      { from: 'Ouarzazate', to: 'Merzouga' },
      { from: 'Marrakech', to: 'Ouarzazate' },
    ],
    image: IMG('ouarzazate'),
  },
  tetouan: {
    slug: 'tetouan', name: 'Tetouan',
    airport: 'TNG - Tangier Ibn Battouta (1h)', region: 'Tangier-Tetouan-Al Hoceima',
    description: 'Car rental and transfer in Tetouan — Mediterranean city transfers, Chefchaouen access, and northern Morocco exploration.',
    longDescription: 'Tetouan is a beautiful city in northern Morocco with a UNESCO-listed Medina and strong Andalusian influences. Golden Trans provides easy transfers from Tangier Airport to Tetouan and surrounding areas.',
    landmarks: ['Tetouan Medina', 'Royal Palace', 'Ethnographic Museum', 'Martil Beach', 'Cabo Negro'],
    popularRoutes: [
      { from: 'Tangier', to: 'Tetouan' },
      { from: 'Tetouan', to: 'Chefchaouen' },
      { from: 'Tetouan', to: 'Martil' },
      { from: 'Tetouan', to: 'M\'diq' },
    ],
    image: IMG('tetouan'),
  },
  asilah: {
    slug: 'asilah', name: 'Asilah',
    airport: 'TNG - Tangier Ibn Battouta (45min)', region: 'Tangier-Tetouan-Al Hoceima',
    description: 'Car rental and transfer in Asilah — coastal town with whitewashed streets, murals, and summer arts festivals.',
    longDescription: 'Asilah is a picturesque coastal town known for its white and blue medina, vibrant murals painted during the annual arts festival, and relaxed Atlantic beach atmosphere. Golden Trans serves Asilah from Tangier and Larache.',
    landmarks: ['Asilah Medina', 'Ramparts & Mural Walls', 'Palais Raissuli', 'Asilah Beach', 'Parish Church'],
    popularRoutes: [
      { from: 'Tangier', to: 'Asilah' },
      { from: 'Asilah', to: 'Larache' },
      { from: 'Asilah', to: 'Rabat' },
      { from: 'Tangier Airport (TNG)', to: 'Asilah' },
    ],
    image: IMG('asilah'),
  },
  eljadida: {
    slug: 'eljadida', name: 'El Jadida',
    airport: 'CMN - Casablanca Mohammed V (1h)', region: 'Casablanca-Settat',
    description: 'Car rental and transfer in El Jadida — Portuguese heritage city, beaches, and Mazagan resort access.',
    longDescription: 'El Jadida is a UNESCO World Heritage site with its Portuguese Cistern and fortified city walls. It is also home to the Mazagan Beach Resort. Golden Trans offers convenient transfers from Casablanca Airport.',
    landmarks: ['Portuguese Cistern', 'Fortress of Mazagan', 'El Jadida Beach', 'Mazagan Beach Resort', 'Old City Walls'],
    popularRoutes: [
      { from: 'Casablanca Airport (CMN)', to: 'El Jadida' },
      { from: 'El Jadida', to: 'Casablanca' },
      { from: 'El Jadida', to: 'Safi' },
      { from: 'El Jadida', to: 'Oualidia' },
    ],
    image: IMG('el-jadida'),
  },
  ifrane: {
    slug: 'ifrane', name: 'Ifrane',
    airport: 'FEZ - Fes Saïss (1h)', region: 'Fes-Meknes',
    description: 'Car rental and transfer in Ifrane — Morocco\'s alpine resort, ski station, and cedar forest gateway.',
    longDescription: 'Ifrane is known as "Little Switzerland" for its European-style architecture and snow-capped winters. It is home to Al Akhawayn University and the nearby Michlifen ski resort. Golden Trans provides transfers from Fes Airport.',
    landmarks: ['Al Akhawayn University', 'Michlifen Ski Resort', 'Cedar Forest (Azrou)', 'Lion Stone', 'Ifrane National Park'],
    popularRoutes: [
      { from: 'Fes', to: 'Ifrane' },
      { from: 'Ifrane', to: 'Azrou' },
      { from: 'Ifrane', to: 'Meknes' },
      { from: 'Fes Airport (FEZ)', to: 'Ifrane' },
    ],
    image: IMG('ifrane'),
  },
  dakhla: {
    slug: 'dakhla', name: 'Dakhla',
    airport: 'VIL - Dakhla', region: 'Dakhla-Oued Ed-Dahab',
    description: 'Car rental and transfer in Dakhla — kitesurfing capital, coastal lagoon transport, and southern Morocco expeditions.',
    longDescription: 'Dakhla is a world-renowned kitesurfing and windsurfing destination on a peninsula in southern Morocco. Its lagoon and constant winds attract water sports enthusiasts year-round. Golden Trans offers reliable airport and city transfers.',
    landmarks: ['Dakhla Lagoon', 'Dragon Island', 'Dakhla Beach', 'Km 25 Kite Spot', 'Oum Lbouer'],
    popularRoutes: [
      { from: 'Dakhla Airport (VIL)', to: 'Dakhla City Center' },
      { from: 'Dakhla', to: 'Laayoune' },
      { from: 'Dakhla', to: 'Dakhla Lagoon' },
      { from: 'Dakhla', to: 'Km 25 Kite Beach' },
    ],
    image: IMG('dakhla'),
  },
  oujda: {
    slug: 'oujda', name: 'Oujda',
    airport: 'OUD - Oujda Angads', region: 'Oriental',
    description: 'Car rental and transfer in Oujda — eastern gateway city, Algerian border access, and Saidia beach resort transfers.',
    longDescription: 'Oujda is the capital of the Oriental region and a historic crossroads between Morocco and Algeria. Golden Trans provides transfers from Oujda Angads Airport to the city, Saidia beach resort, and nearby attractions.',
    landmarks: ['Lalla Aicha Park', 'Oujda Medina', 'Sidi Yahya Mosque', 'Saidia Beach', 'Zegzel Gorge'],
    popularRoutes: [
      { from: 'Oujda Airport (OUD)', to: 'Oujda City Center' },
      { from: 'Oujda', to: 'Saidia' },
      { from: 'Oujda', to: 'Nador' },
      { from: 'Oujda', to: 'Berkane' },
    ],
    image: IMG('oujda'),
  },
  merzouga: {
    slug: 'merzouga', name: 'Merzouga',
    airport: 'OZZ - Ouarzazate (4h) / RAK - Marrakech (6h)', region: 'Drâa-Tafilalet',
    description: 'Car rental and transfer to Merzouga — Erg Chebbi dunes, desert camp access, and Sahara safari gateway.',
    longDescription: 'Merzouga is the gateway to the magnificent Erg Chebbi sand dunes, one of Morocco\'s most iconic landscapes. Golden Trans offers desert transfers for a magical Sahara experience including camel rides and luxury desert camps.',
    landmarks: ['Erg Chebbi Dunes', 'Merzouga Lake', 'Khamlia Gnawa Village', 'Rissani Market', 'Tafilalet Palm Grove'],
    popularRoutes: [
      { from: 'Marrakech', to: 'Merzouga' },
      { from: 'Fes', to: 'Merzouga' },
      { from: 'Ouarzazate', to: 'Merzouga' },
      { from: 'Merzouga', to: 'Rissani' },
    ],
    image: IMG('merzouga'),
  },
  aitbenhaddou: {
    slug: 'aitbenhaddou', name: 'Ait Ben Haddou',
    airport: 'OZZ - Ouarzazate (30min)', region: 'Drâa-Tafilalet',
    description: 'Car rental and transfer to Ait Ben Haddou — UNESCO World Heritage ksar, film location, and desert gateway.',
    longDescription: 'Ait Ben Haddou is a stunning fortified village (ksar) on the former caravan route between the Sahara and Marrakech. A UNESCO World Heritage site, it has been featured in Game of Thrones, Gladiator, and Lawrence of Arabia.',
    landmarks: ['Ksar of Ait Ben Haddou', 'Atlas Mountains Viewpoint', 'Télouet Kasbah', 'Ounila Valley', 'Fint Oasis'],
    popularRoutes: [
      { from: 'Ouarzazate', to: 'Ait Ben Haddou' },
      { from: 'Marrakech', to: 'Ait Ben Haddou' },
      { from: 'Ait Ben Haddou', to: 'Merzouga' },
      { from: 'Ait Ben Haddou', to: 'Ouarzazate Airport (OZZ)' },
    ],
    image: IMG('ait-ben-haddou'),
  },
}

export const POPULAR_CITIES = [
  CITIES_DATA.marrakech,
  CITIES_DATA.casablanca,
  CITIES_DATA.rabat,
  CITIES_DATA.fes,
  CITIES_DATA.tangier,
  CITIES_DATA.agadir,
  CITIES_DATA.chefchaouen,
  CITIES_DATA.essaouira,
  CITIES_DATA.meknes,
  CITIES_DATA.ouarzazate,
  CITIES_DATA.tetouan,
  CITIES_DATA.asilah,
  CITIES_DATA.eljadida,
  CITIES_DATA.ifrane,
  CITIES_DATA.dakhla,
  CITIES_DATA.oujda,
  CITIES_DATA.merzouga,
  CITIES_DATA.aitbenhaddou,
]
